name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-preview:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: subdir/pingcap/yarn.lock
        
    - name: Build
      run: |
        echo "start build"
        cd pingcap
        yarn
        yarn build
    
    - name: deploy file to preview server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.PREVIEW_EN_SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.PREVIEW_EN_IP }}
        REMOTE_USER: ubuntu
        SOURCE: pingcap/
        TARGET: /home/ubuntu/preview-en/wordpress/wp-content/themes/test
        EXCLUDE: node_modules
